"""Path-based rate limiting for auth endpoints.

Deliberately dependency-free and in-process. That means limits are per
instance and reset on deploy — enough to stop credential stuffing and reset-
email abuse from one IP, not enough to coordinate across replicas. If you
scale past one instance and care, move the buckets to Redis; the interface
here won't change.

It is a middleware rather than a decorator because the routes being protected
are generated by fastapi-users, so there is nothing of ours to decorate.
"""

import time
from collections import deque
from collections.abc import Awaitable, Callable

from fastapi import FastAPI, Request, Response
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from app.config import Settings

# Upper bound on distinct (route, IP) buckets held in memory.
MAX_TRACKED_KEYS = 10_000


def parse_rule(rule: str) -> tuple[int, int]:
    """'10/minute' -> (10, 60). Accepts second|minute|hour|day."""
    amount, _, period = rule.partition("/")
    seconds = {
        "second": 1,
        "minute": 60,
        "hour": 3600,
        "day": 86400,
    }
    key = period.strip().rstrip("s").lower()
    if key not in seconds:
        raise ValueError(f"Unknown rate limit period: {rule!r}")
    return int(amount), seconds[key]


def client_ip(request: Request) -> str:
    """The caller's IP, as Railway's edge proxy reports it.

    Railway overwrites X-Real-IP on every request, so a client cannot forge
    it. X-Forwarded-For is deliberately ignored: its left-most entry is
    whatever the client claims unless every proxy in front strips it, and
    trusting it lets an attacker rotate fake IPs past every limit here.
    """
    real_ip = request.headers.get("X-Real-IP")
    if real_ip:
        return real_ip.strip()
    return request.client.host if request.client else "unknown"


class RateLimitMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, settings: Settings) -> None:
        super().__init__(app)
        # (method, exact path) -> rule
        self._rules: dict[tuple[str, str], tuple[int, int]] = {
            ("POST", "/api/auth/login"): parse_rule(settings.RATE_LIMIT_LOGIN),
            # The iOS app's login. Same password check, so the same limit.
            ("POST", "/api/auth/bearer/login"): parse_rule(
                settings.RATE_LIMIT_LOGIN
            ),
            ("POST", "/api/auth/register"): parse_rule(
                settings.RATE_LIMIT_REGISTER
            ),
            ("POST", "/api/auth/forgot-password"): parse_rule(
                settings.RATE_LIMIT_FORGOT_PASSWORD
            ),
            ("POST", "/api/auth/reset-password"): parse_rule(
                settings.RATE_LIMIT_FORGOT_PASSWORD
            ),
            # Authed, but this runs before the route's dependencies resolve, so
            # it is what stops a flood from making us decode megabyte bodies.
            # The per-user window and daily ceiling live in the route itself.
            ("POST", "/api/ai/meal-photo"): parse_rule(
                settings.RATE_LIMIT_MEAL_PHOTO
            ),
            # Both take the current password, so both are guessing oracles.
            ("PATCH", "/api/users/me"): parse_rule(settings.RATE_LIMIT_LOGIN),
            ("DELETE", "/api/users/me"): parse_rule(settings.RATE_LIMIT_LOGIN),
        }
        self._hits: dict[str, deque[float]] = {}

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        rule = self._rules.get((request.method, request.url.path))
        if rule is None:
            return await call_next(request)

        limit, window = rule
        bucket_key = f"{request.method} {request.url.path} {client_ip(request)}"
        now = time.monotonic()
        hits = self._hits.get(bucket_key)
        if hits is None:
            self._evict(now)
            hits = self._hits[bucket_key] = deque()
        while hits and now - hits[0] > window:
            hits.popleft()

        if len(hits) >= limit:
            retry_after = int(window - (now - hits[0])) + 1
            return JSONResponse(
                status_code=429,
                content={"detail": "Too many requests. Try again shortly."},
                headers={"Retry-After": str(retry_after)},
            )

        hits.append(now)
        return await call_next(request)

    def _evict(self, now: float) -> None:
        """Keep memory bounded no matter how many distinct IPs show up.

        First drop buckets whose hits have all aged out of the longest
        window; if that still leaves too many, drop the oldest-inserted keys.
        """
        if len(self._hits) < MAX_TRACKED_KEYS:
            return
        longest = max(window for _, window in self._rules.values())
        for key in [k for k, q in self._hits.items() if not q or now - q[-1] > longest]:
            del self._hits[key]
        while len(self._hits) >= MAX_TRACKED_KEYS:
            del self._hits[next(iter(self._hits))]
