"""Path-based rate limiting for auth endpoints.

Deliberately dependency-free and in-process. That means limits are per
instance and reset on deploy — enough to stop credential stuffing and reset-
email abuse from one IP, not enough to coordinate across replicas. If you
scale past one instance and care, move the buckets to Redis; the interface
here won't change.

It is a middleware rather than a decorator because the routes being protected
are generated by fastapi-users, so there is nothing of ours to decorate.
"""

import time
from collections import defaultdict, deque
from collections.abc import Awaitable, Callable

from fastapi import FastAPI, Request, Response
from fastapi.responses import JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from app.config import Settings


def parse_rule(rule: str) -> tuple[int, int]:
    """'10/minute' -> (10, 60). Accepts second|minute|hour|day."""
    amount, _, period = rule.partition("/")
    seconds = {
        "second": 1,
        "minute": 60,
        "hour": 3600,
        "day": 86400,
    }
    key = period.strip().rstrip("s").lower()
    if key not in seconds:
        raise ValueError(f"Unknown rate limit period: {rule!r}")
    return int(amount), seconds[key]


def client_ip(request: Request) -> str:
    """Railway terminates TLS and proxies, so trust X-Forwarded-For's first hop.

    Only safe because the app is always behind Railway's proxy. Exposed
    directly to the internet, this header is attacker-controlled.
    """
    forwarded = request.headers.get("X-Forwarded-For")
    if forwarded:
        return forwarded.split(",")[0].strip()
    return request.client.host if request.client else "unknown"


class RateLimitMiddleware(BaseHTTPMiddleware):
    def __init__(self, app, settings: Settings) -> None:
        super().__init__(app)
        # (method, exact path) -> rule
        self._rules: dict[tuple[str, str], tuple[int, int]] = {
            ("POST", "/api/auth/login"): parse_rule(settings.RATE_LIMIT_LOGIN),
            ("POST", "/api/auth/register"): parse_rule(
                settings.RATE_LIMIT_REGISTER
            ),
            ("POST", "/api/auth/forgot-password"): parse_rule(
                settings.RATE_LIMIT_FORGOT_PASSWORD
            ),
            ("POST", "/api/auth/reset-password"): parse_rule(
                settings.RATE_LIMIT_FORGOT_PASSWORD
            ),
        }
        self._hits: dict[str, deque[float]] = defaultdict(deque)

    async def dispatch(
        self,
        request: Request,
        call_next: Callable[[Request], Awaitable[Response]],
    ) -> Response:
        rule = self._rules.get((request.method, request.url.path))
        if rule is None:
            return await call_next(request)

        limit, window = rule
        bucket_key = f"{request.method} {request.url.path} {client_ip(request)}"
        now = time.monotonic()
        hits = self._hits[bucket_key]
        while hits and now - hits[0] > window:
            hits.popleft()

        if len(hits) >= limit:
            retry_after = int(window - (now - hits[0])) + 1
            return JSONResponse(
                status_code=429,
                content={"detail": "Too many requests. Try again shortly."},
                headers={"Retry-After": str(retry_after)},
            )

        hits.append(now)
        return await call_next(request)
